django_sample/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hello/', include('hello.urls', namespace='hello')),
    url(r'^horse/', include('horse.urls', namespace='horse')),
]

hello/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^$', views.hello_world, name='hello_world'),
    url(r'^template/$', views.hello_template, name='hello_template'),
]

horse/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^delete/$', views.delete, name='delete'),
    url(r'^edit/(?P<editing_id>\d+)/$', views.edit, name='edit'),
]

hello/models.py
from django.db import models

# Create your models here.

horse/models.py
from django.db import models

# Create your models here.
class Horse(models.Model):
    bamei = models.CharField(max_length=255)
    barei = models.IntegerField(default=1)
    class_cd = models.IntegerField(default=1)
    sex = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return u"{0}:{1}... ".format(self.id, self.bamei)

horse/forms.py
from django import forms


class HorseForm(forms.Form):
    bamei = forms.CharField(
        label='馬名',
        max_length=255,
        required=True,
        widget=forms.TextInput()
    )
    
    barei = forms.IntegerField(
        label='馬齢',
        min_value=1,
        max_value=99,
        required=True,
    )
    
    class_cd = forms.IntegerField(
        label='クラス',
        min_value=1,
        max_value=10,
        required=True,
    )
    

hello/views.py
from datetime import datetime

from django.http.response import HttpResponse
from django.shortcuts import render

# Create your views here.
def hello_world(request):
    return HttpResponse('Hello World')

def hello_template(request):
    
    time = {
            'hour': datetime.now().hour,
            'message': 'Sample message',
            }
    
    return render(request, 'index.html', time)

horse/views.py
from django.shortcuts import (
    render, 
    redirect, 
    get_object_or_404,
    ) 
from django.http import HttpResponse
from .models import Horse
from .forms import HorseForm  
from django.views.decorators.http import require_POST
import logging


# Create your views here.
def index(request):
    
    logger = logging.getLogger('command')
    logger.debug("test")
    
    d = {
        'horses': Horse.objects.all(),
    }
    return render(request, 'horse/index.html', d)

def add(request):
    form = HorseForm(request.POST or None)
    if form.is_valid():
        Horse.objects.create(**form.cleaned_data)
        return redirect('horse:index')

    d = {
        'form': form,
    }
    return render(request, 'horse/edit.html', d)

def edit(request, editing_id):
    horse = get_object_or_404(Horse, id=editing_id)
    if request.method == 'POST':
        form = HorseForm(request.POST)
        if form.is_valid():
            horse.bamei = form.cleaned_data['bamei']
            horse.save()
            return redirect('horse:index')
    else:
        logger = logging.getLogger('command')
        logger.debug("edit")
        logger.debug(horse.bamei)
        form = HorseForm({'bamei': horse.bamei,
                          'barei': horse.barei,
                          'class_cd': horse.class_cd,
                          })
    d = {
        'form': form,
    }
    
    return render(request, 'horse/edit.html', d)

@require_POST
def delete(request):
    delete_ids = request.POST.getlist('delete_ids')
    if delete_ids:
        Horse.objects.filter(id__in=delete_ids).delete()
    return redirect('horse:index')    

templates/base.html
<!DOCTYPE html>
<html>
<head lang="ja">
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

templates/horse/edit.html
{% extends "base.html" %}

{% block body %}
   <a href="{% url 'horse:index' %}">一覧画面へ</a>
    <form action="" method="post">
        {{ form.errors.message }}
        <label>{{ form.bamei.label }}{{ form.bamei }}</label><br/>
        <label>{{ form.barei.label }}{{ form.barei }}</label><br/>
        <label>{{ form.class_cd.label }}{{ form.class_cd }}</label><br/>
        {% csrf_token %}
        <input type="submit" value="登録">
    </form>
{% endblock %}

templates/horse/index.html
{% extends "base.html" %}

{% block body %}
  <a href="{% url 'horse:add' %}">登録画面へ</a>{# 追加する #}
  <form method="post" action="{% url 'horse:delete' %}">
    <table border="1">
      <thead>
        <tr>
          <th>　</th>
          <th>horse</th>
          <th>barei</th>
          <th>class_cd</th>
          <th>created_at</th>
          <th>updated_at</th>
          <th>　</th>
        </tr>
      </thead>
      <tbody>
        {% for horse in horses %}
          <tr>
          	<td><input type="checkbox" name="delete_ids" value="{{ horse.id }}"></td>
            <td>{{ horse.bamei }}</td>
            <td>{{ horse.barei }}</td>
            <td>{{ horse.class_cd }}</td>
            <td>{{ horse.created_at }}</td>
            <td>{{ horse.updated_at }}</td>
            <td><a href="{% url 'horse:edit' horse.id %}">更新</a></td>            
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% csrf_token %}
    <input type="submit" value="削除">
  </form>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html>
<head lang="ja">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
Hello Template!<br>
{{ hour }}時です。<br>
{{ message }}
</body>
</html>